# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731获取正式讲次列表.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731获取正式讲次列表(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/walletChangeList")
            .get(
                "https://api-wx.yangcong345.com/primary_account/course/walletChangeList"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/weeks",
                    "accept-encoding": "identity",
                    "range": "item=0-19",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzI0NjAyfQ.u0MjIyJBVhmXjFYHD3gqB253BFbLsOCEgf7iTp4WayY",
                    "Postman-Token": "a7b0a876-6342-41bb-8253-f1bfc8e1e33d",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 206)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731获取正式讲次列表().test_start()
