# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731提交完成结课测评.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731提交完成结课测评(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam")
            .get(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam"
            )
            .with_params(
                **{
                    "lessonType": "finalExam",
                    "lessonModuleId": "5f0d83dfbe65476c2b9c7545",
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "testPaperId": "0f857100-c0f7-11ea-8045-b12bc88dde59",
                    "lessonId": "5f07dfe81095139db49acc11",
                    "isOpen": "false",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "referer": "https://yangcong345.com/mp_exercise/app/exam",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "b583e1a8-faf1-48d9-9b2f-9ac507d48c83",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731提交完成结课测评().test_start()
