# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731摸底测试列表.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731摸底测试列表(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam")
            .get(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam"
            )
            .with_params(
                **{
                    "lessonType": "preExam",
                    "lessonModuleId": "5f16d6fef2f45f2c4beffb04",
                    "classId": "5f16d5871ffc282549a07662",
                    "testPaperId": "b40223d0-c0ee-11ea-8045-b12bc88dde59",
                    "lessonId": "5f16d6fef2f45f1129effb03",
                    "isOpen": "false",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "referer": "https://yangcong345.com/mp_exercise/index.html?classId=5f16d5871ffc282549a07662&d_app_version=5.32.0&entrance=exam&firstScene=&from=courseInt&goalId=&isMultiProblem=true&lessonId=5f16d6fef2f45f1129effb03&lessonModuleId=5f16d6fef2f45f2c4beffb04&lessonName=%E6%91%B8%E5%BA%95%E6%B5%8B%E8%AF%95&lessonType=preExam&moudleType=CBExam&platform=app&psToken=eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMDIwfQ.r58cZnE9KI2lpcz8mOkidIUUTHwCDM3tFiW447yTk_M&semester=%E4%B8%89%E5%B9%B4%E7%BA%A7&testPaperId=b40223d0-c0ee-11ea-8045-b12bc88dde59&u_role=student&u_user=5e3afbd5af65480001ce2298&videoId=&videoName=&device=08BE5209-54CA-419A-9490-8EA9EED6B3B9&openUUID=fa34e7ef7bf60da55da79b66d4e90588d21e745e&userId=5e3afbd5af65480001ce2298&appVersion=5.32.0&platform=ios&phoneModel=iPad11,3&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlM2FmYmQ1YWY2NTQ4MDAwMWNlMjI5OCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNTk2MTg2MjYyLCJleHAiOjE1OTg3NzkwMTF9.B9KOjA08yHrjFOMZ8JGtQtqjPNqQFpD91peMKvSKSnc&clientChannel=appstore&clientType=ios-app&environment=release&exerciseDebug=0",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMDIwfQ.r58cZnE9KI2lpcz8mOkidIUUTHwCDM3tFiW447yTk_M",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "1912b61c-66b8-4811-b0ba-d0899eb9c77c",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731摸底测试列表().test_start()
