# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731大课获取讲次列表.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731大课获取讲次列表(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/courseV2InOneClass")
            .get(
                "https://api-wx.yangcong345.com/primary_account/course/courseV2InOneClass"
            )
            .with_params(**{"platform": "app", "classId": "5f23e7414b246b32da120c62"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/weeks",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzI0NjAyfQ.u0MjIyJBVhmXjFYHD3gqB253BFbLsOCEgf7iTp4WayY",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "1604b489-407d-4031-8bfd-938f496ecb8f",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731大课获取讲次列表().test_start()
