# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731跳转家长课堂更新卡片状态.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731跳转家长课堂更新卡片状态(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/learnV2/updateLiveBroadcastEvent")
            .post(
                "https://api-wx.yangcong345.com/primary_account/learnV2/updateLiveBroadcastEvent"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "content-type": "application/json;charset=utf-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/days",
                    "content-length": "219",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "a59ca484-ea46-48ab-ba77-d95991b17041",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .with_json(
                {
                    "updateType": "watch",
                    "userId": "5e3afbd5af65480001ce2298",
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "lessonId": "5f07dfe81095137bd99acc06",
                    "moduleId": "5f11cf08e07af762f241a62b",
                    "moduleDetail": {"id": "1084345", "type": "roomId"},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.result", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731跳转家长课堂更新卡片状态().test_start()
