# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731班级列表.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731班级列表(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/userCourse")
            .get("https://api-wx.yangcong345.com/primary_account/course/userCourse")
            .with_params(
                **{
                    "sign": "D7E63860C2A446F379C95860D81294985F23DFC7primary",
                    "context": "VTJGc2RHVmtYMStneXpBVWFBRUNMNmZ0U2pleVcvaWdXMno0YnBiQ0RJNDd6Y1JEblU5Wkk1THQ0ZlNiUm5WbUFrcCs2bUdaS2xiQmlDNVJJZzlzRlErdXgwdENEa01iTU5PM0hwZGEwL1E9",
                    "crypto": "true",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/classesIos",
                    "accept-language": "zh-cn",
                    "x-crypto-api": "true",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIyNTY3fQ.rEPEkH3_nM1TIDQTud13pYpnYgWsQmuKLHzZsKJN3x4",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "237c4e20-52d2-4943-af48-286c8c9e5916",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal(
                "body.sign", "4BD109BABF431C1BDB1C1B3B36599B0A5F23EC4Dprimary"
            )
            .assert_equal("body.crypto", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731班级列表().test_start()
