# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731答题完成页.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731答题完成页(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/courseProblem")
            .get("https://api-wx.yangcong345.com/primary_account/course/courseProblem")
            .with_params(
                **{
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "topicId": "6e447e70-b71c-11e8-9ff2-f7ed962873d2",
                    "lessonId": "5f07dfe810951356079acbee",
                    "moduleId": "5f07dfe8109513671f9acbf1",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/mp_exercise/app/complete_v1",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "a5696941-5814-4045-9995-3e23888dcfcc",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731答题完成页().test_start()
