# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731摸底测试结果页.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731摸底测试结果页(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam")
            .get(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam"
            )
            .with_params(
                **{
                    "lessonType": "preExam",
                    "lessonModuleId": "5f0828ef10951323a49acf10",
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "testPaperId": "b40223d0-c0ee-11ea-8045-b12bc88dde59",
                    "lessonId": "5f07dfe81095138e969acbeb",
                    "isOpen": "false",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "referer": "https://yangcong345.com/mp_exercise/app/exam",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMjM3fQ.kealwubPAQr0AAWRuA9zJ4bK5iDBa-MZxkexqyBtSZo",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "3529800d-a52b-4f40-9cf2-bc3ade03e9a1",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731摸底测试结果页().test_start()
