# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731获取大课班级.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731获取大课班级(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/classInfoById")
            .get("https://api-wx.yangcong345.com/primary_account/course/classInfoById")
            .with_params(**{"classId": "5f23e7414b246b32da120c62"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/?scene=systemicClass&sceneParamsStr=%7B%22classId%22:%225f23e7414b246b32da120c62%22,%22unlockMode%22:%22week%22,%22curriculumVersion%22:2%7D&device=08BE5209-54CA-419A-9490-8EA9EED6B3B9&openUUID=fa34e7ef7bf60da55da79b66d4e90588d21e745e&userId=5e3afbd5af65480001ce2298&appVersion=5.32.0&platform=ios&phoneModel=iPad11,3&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlM2FmYmQ1YWY2NTQ4MDAwMWNlMjI5OCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNTk2MTg2MjYyLCJleHAiOjE1OTg3ODA1OTN9.UijxgGygzilaQdZ3b-8stXvPyiVRRO3uV9TNsgo5yrw&clientChannel=appstore&clientType=ios-app&environment=release&exerciseDebug=0",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzI0NjAyfQ.u0MjIyJBVhmXjFYHD3gqB253BFbLsOCEgf7iTp4WayY",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "d9e381cb-aa6c-41bd-a244-ba8deb28f0bb",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731获取大课班级().test_start()
