# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731上传拓展题.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731上传拓展题(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/userUpload")
            .post("https://api-wx.yangcong345.com/primary_account/course/userUpload")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "content-type": "application/json;charset=utf-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/lessonPractice",
                    "content-length": "196",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "b1fd6214-0ee1-4520-bb79-bee7f17bdc5b",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .with_json(
                {
                    "lessonId": "5f07dfe810951356079acbee",
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "update": False,
                    "userUpload": [
                        {
                            "url": "https://wx-static.yangcong345.com/expand/15961880773108081.jpg"
                        }
                    ],
                    "platform": "app",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731上传拓展题().test_start()
