# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731摸底测试答题.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731摸底测试答题(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam-submit")
            .post(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam-submit"
            )
            .with_headers(
                **{
                    "accept": "application/json",
                    "origin": "https://yangcong345.com",
                    "content-type": "application/json;charset=UTF-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMjM3fQ.kealwubPAQr0AAWRuA9zJ4bK5iDBa-MZxkexqyBtSZo",
                    "referer": "https://yangcong345.com/mp_exercise/app/exam",
                    "content-length": "947",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "34fb7c6e-3fc2-41da-af64-56ad621be69a",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .with_json(
                {
                    "lessonModuleId": "5f0828ef10951323a49acf10",
                    "lessonType": "preExam",
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "testPaperId": "b40223d0-c0ee-11ea-8045-b12bc88dde59",
                    "lessonId": "5f07dfe81095138e969acbeb",
                    "answers": [
                        {
                            "id": "077cfb20-aae7-11ea-bc4e-3faf3749bac1",
                            "score": 12.5,
                            "answer": ["$54$，$61$"],
                            "state": False,
                        },
                        {
                            "id": "471a3a90-aae7-11ea-b3bf-8fd7c41e4462",
                            "score": 12.5,
                            "answer": ["$7$"],
                            "state": False,
                        },
                        {
                            "id": "80fc09f0-aae7-11ea-aa4b-2d95eee0c111",
                            "score": 12.5,
                            "answer": ["$53$"],
                            "state": True,
                        },
                        {
                            "id": "5bf8f0f0-aae7-11ea-b3bf-8fd7c41e4462",
                            "score": 12.5,
                            "answer": ["$22$", "$63$"],
                            "state": False,
                        },
                        {
                            "id": "8c92ce20-aae7-11ea-b3bf-8fd7c41e4462",
                            "score": 12.5,
                            "answer": ["$2$"],
                            "state": False,
                        },
                        {
                            "id": "d9fc6050-aaf0-11ea-bc4e-3faf3749bac1",
                            "score": 12.5,
                            "answer": ["$33$"],
                            "state": False,
                        },
                        {
                            "id": "ec214de0-aaf0-11ea-aa4b-2d95eee0c111",
                            "score": 12.5,
                            "answer": ["$66$"],
                            "state": False,
                        },
                        {
                            "id": "feddc080-aaf0-11ea-b3bf-8fd7c41e4462",
                            "score": 12.5,
                            "answer": ["$33$"],
                            "state": False,
                        },
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731摸底测试答题().test_start()
