# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731大课结课报告.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731大课结课报告(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/learnReport/course/end-report")
            .get(
                "https://api-wx.yangcong345.com/primary_account/learnReport/course/end-report"
            )
            .with_params(
                **{
                    "platform": "app",
                    "classId": "5f23e7414b246b32da120c62",
                    "moduleId": "5f0d6d38be6547665a9c7250",
                    "lessonId": "5f07e1b4109513cf629acc22",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/endReport",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzI0ODYzfQ.vU-I2YwchJNPymsy3S0G2kgWOoDxZtf95E6oaH2W22A",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "b1d65078-d79a-4601-b18c-0bc937fa5469",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731大课结课报告().test_start()
