# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731更新课程token.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731更新课程Token(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/classCourse/uploadToken")
            .post(
                "https://api-wx.yangcong345.com/primary_account/classCourse/uploadToken"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "content-type": "application/x-www-form-urlencoded",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/lessonPractice",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "content-length": "0",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "2f34ad32-7002-49a9-acd3-dc87169c17d4",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .with_data({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.ok", True)
            .assert_equal(
                "body.token",
                "cIz1V358Ef7woh_xZ0cH5mTGWv-Q7fHf71saOcjn:pPKz7-noAYSIKYbyF8PSt8zeuPM=:eyJzY29wZSI6InljLXdlY2hhdCIsImRlYWRsaW5lIjoxNTk2MTkxNTI5fQ==",
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731更新课程Token().test_start()
