# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731结课测评.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731结课测评(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam")
            .get(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam"
            )
            .with_params(
                **{
                    "lessonType": "finalExam",
                    "lessonModuleId": "5f0d83dfbe65476c2b9c7545",
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "testPaperId": "0f857100-c0f7-11ea-8045-b12bc88dde59",
                    "lessonId": "5f07dfe81095139db49acc11",
                    "isOpen": "false",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "referer": "https://yangcong345.com/mp_exercise/index.html?classId=5f0dbf98e08ce80fd5fa97d7&d_app_version=5.32.0&entrance=exam&firstScene=&from=courseInt&goalId=&isMultiProblem=true&lessonId=5f07dfe81095139db49acc11&lessonModuleId=5f0d83dfbe65476c2b9c7545&lessonName=%E7%BB%93%E8%AF%BE%E6%B5%8B%E8%AF%84&lessonType=finalExam&moudleType=CBExam&platform=app&psToken=eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo&semester=%E4%B8%89%E5%B9%B4%E7%BA%A7&testPaperId=0f857100-c0f7-11ea-8045-b12bc88dde59&u_role=student&u_user=5e3afbd5af65480001ce2298&videoId=&videoName=&device=08BE5209-54CA-419A-9490-8EA9EED6B3B9&openUUID=fa34e7ef7bf60da55da79b66d4e90588d21e745e&userId=5e3afbd5af65480001ce2298&appVersion=5.32.0&platform=ios&phoneModel=iPad11,3&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlM2FmYmQ1YWY2NTQ4MDAwMWNlMjI5OCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNTk2MTg2MjYyLCJleHAiOjE1OTg3NzkxMjR9.mt3ZQdQl5Own7eCbPbQKmOzBbaY-9iKLp1gJ2921360&clientChannel=appstore&clientType=ios-app&environment=release&exerciseDebug=0",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "e64444a5-acf7-4a1a-ae7d-d65714de1e89",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731结课测评().test_start()
