# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731传课程解锁时间.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731传课程解锁时间(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/user/unlock-times")
            .post(
                "https://api-wx.yangcong345.com/primary_account/course/user/unlock-times"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "content-type": "application/json;charset=utf-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzI0NjAyfQ.u0MjIyJBVhmXjFYHD3gqB253BFbLsOCEgf7iTp4WayY",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/weeks",
                    "content-length": "60",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "5656957e-12a8-4cdd-b71e-754cc6a4786f",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .with_json(
                {"classId": "5f23e7414b246b32da120c62", "unlockTimes": [1, 3, 5]}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731传课程解锁时间().test_start()
