# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0731获取第一节习题.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0731获取第一节习题(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/courseProblem")
            .get("https://api-wx.yangcong345.com/primary_account/course/courseProblem")
            .with_params(
                **{
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "topicId": "6e447e70-b71c-11e8-9ff2-f7ed962873d2",
                    "lessonId": "5f07dfe810951356079acbee",
                    "moduleId": "5f07dfe8109513671f9acbf1",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/mp_exercise/?goalId=6e447e70-b71c-11e8-9ff2-f7ed962873d2&videoName=%E5%87%A0%E7%99%BE%E5%87%A0%E5%8D%81%E5%8A%A0%E5%87%A0%E7%99%BE%E5%87%A0%E5%8D%81&entrance=quizzing_v1&lessonId=5f07dfe810951356079acbee&platform=app&videoId=fbc0e3a2-b716-11e8-823c-6b68122db993&moduleId=5f07dfe8109513671f9acbf1&psToken=eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo&semester=3&isMultiProblem=1&classId=5f0dbf98e08ce80fd5fa97d7&device=08BE5209-54CA-419A-9490-8EA9EED6B3B9&openUUID=fa34e7ef7bf60da55da79b66d4e90588d21e745e&userId=5e3afbd5af65480001ce2298&appVersion=5.32.0&platform=ios&phoneModel=iPad11,3&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlM2FmYmQ1YWY2NTQ4MDAwMWNlMjI5OCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNTk2MTg2MjYyLCJleHAiOjE1OTg3NzkxMjR9.mt3ZQdQl5Own7eCbPbQKmOzBbaY-9iKLp1gJ2921360&clientChannel=appstore&clientType=ios-app&environment=release&exerciseDebug=0",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI3NzIzMzM4fQ.xRItRjFdVoKqKsU8dMQoPLoxod8uUGsli0Jf9VSsoGo",
                    "accept-encoding": "gzip, deflate, br",
                    "Postman-Token": "5e7d3558-ab45-4501-93d7-79269969d303",
                    "Host": "api-wx.yangcong345.com",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0731获取第一节习题().test_start()
