# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807完成课前导学.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807完成课前导学(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest(
                "/primary_account/video-manager/videos/5f1feaf25eddaa3731129f3c/learn-report"
            )
            .put(
                "https://api-wx.yangcong345.com/primary_account/video-manager/videos/5f1feaf25eddaa3731129f3c/learn-report"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "content-type": "application/json;charset=utf-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/lessonInfo",
                    "content-length": "144",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .with_json(
                {
                    "played": 742,
                    "lessonId": "5f2ccfe6785684e009d8c2af",
                    "classId": "5f0dbf07e08ce8fed7fa97d0",
                    "moduleId": "5f2ccfe678568423d6d8c2b1",
                    "platform": "app",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807完成课前导学().test_start()
