# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0806pc登录.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0806Pc登录(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/passport/pcAuth")
            .post("https://api-primary.yangcong345.com/primary_account/passport/pcAuth")
            .with_headers(
                **{
                    "content-length": "42",
                    "accept": "application/json, text/plain, */*",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://yangcong345.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://yangcong345.com/xiaoxue/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"phone": "18524635227", "captcha": "875369"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0806Pc登录().test_start()
