# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0806获取用户信息.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0806获取用户信息(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/passport/getUserInfo")
            .get(
                "https://api-primary.yangcong345.com/primary_account/passport/getUserInfo"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJwY0g1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MjIzNzU3fQ.IprFPMez09MzYxUj3ygS50QtvQXHt2xg_WBcmxfOJ1U",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "origin": "https://yangcong345.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://yangcong345.com/xiaoxue/courses",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0806获取用户信息().test_start()
