# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807结课测评.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807结课测评(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam")
            .get(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam"
            )
            .with_params(
                **{
                    "lessonType": "finalExam",
                    "lessonModuleId": "5f2ccfe7785684f9bbd8c2d7",
                    "classId": "5f0dbf07e08ce8fed7fa97d0",
                    "testPaperId": "7bd1e920-c0fb-11ea-8045-b12bc88dde59",
                    "lessonId": "5f2ccfe7785684c637d8c2d6",
                    "isOpen": "false",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "referer": "https://yangcong345.com/mp_exercise/index.html?classId=5f0dbf07e08ce8fed7fa97d0&d_app_version=5.33.0&entrance=exam&firstScene=&from=courseInt&goalId=&isMultiProblem=true&lessonId=5f2ccfe7785684c637d8c2d6&lessonModuleId=5f2ccfe7785684f9bbd8c2d7&lessonName=%E7%BB%93%E8%AF%BE%E6%B5%8B%E8%AF%84&lessonType=finalExam&moudleType=CBExam&platform=app&psToken=eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4&semester=%E5%9B%9B%E5%B9%B4%E7%BA%A7&testPaperId=7bd1e920-c0fb-11ea-8045-b12bc88dde59&u_role=student&u_user=5e3afbd5af65480001ce2298&videoId=&videoName=&device=08BE5209-54CA-419A-9490-8EA9EED6B3B9&openUUID=fa34e7ef7bf60da55da79b66d4e90588d21e745e&userId=5e3afbd5af65480001ce2298&appVersion=5.33.0&platform=ios&phoneModel=iPad11,3&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlM2FmYmQ1YWY2NTQ4MDAwMWNlMjI5OCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNTk2NzcxNzA3LCJleHAiOjE1OTkzNjU1NDF9.RSEAC_wtKNxua24TJMHb3lgy6IP0NFbMC7JDXp7A8sk&clientChannel=appstore&clientType=ios-app&environment=release&exerciseDebug=0",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807结课测评().test_start()
