# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807跳转家长课堂.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807跳转家长课堂(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/learnV2/updateLiveBroadcastEvent")
            .post(
                "https://api-wx.yangcong345.com/primary_account/learnV2/updateLiveBroadcastEvent"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "content-type": "application/json;charset=utf-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/days",
                    "content-length": "219",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .with_json(
                {
                    "updateType": "watch",
                    "userId": "5e3afbd5af65480001ce2298",
                    "classId": "5f0dbf07e08ce8fed7fa97d0",
                    "lessonId": "5f2ccfe77856843db5d8c2cb",
                    "moduleId": "5f2ccfe77856842522d8c2cc",
                    "moduleDetail": {"id": "1239253", "type": "roomId"},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.result", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807跳转家长课堂().test_start()
