# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807获取第一节习题.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807获取第一节习题(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/courseProblem")
            .get("https://api-wx.yangcong345.com/primary_account/course/courseProblem")
            .with_params(
                **{
                    "classId": "5f0dbf07e08ce8fed7fa97d0",
                    "topicId": "934ee300-e8b7-11e8-bb48-673502dee17d",
                    "lessonId": "5f2ccfe678568420a4d8c2b3",
                    "moduleId": "5f2ccfe67856846fb4d8c2b6",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/mp_exercise/?goalId=934ee300-e8b7-11e8-bb48-673502dee17d&videoName=%E9%99%A4%E6%95%B0%E6%98%AF%E6%95%B4%E5%8D%81%E6%95%B0%E7%9A%84%E9%99%A4%E6%B3%95(%E4%B8%8A)&entrance=quizzing_v1&lessonId=5f2ccfe678568420a4d8c2b3&platform=app&videoId=6c1d9a76-ac06-11e8-b250-57099ac3d7c5&moduleId=5f2ccfe67856846fb4d8c2b6&psToken=eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4&semester=4&isMultiProblem=1&classId=5f0dbf07e08ce8fed7fa97d0&device=08BE5209-54CA-419A-9490-8EA9EED6B3B9&openUUID=fa34e7ef7bf60da55da79b66d4e90588d21e745e&userId=5e3afbd5af65480001ce2298&appVersion=5.33.0&platform=ios&phoneModel=iPad11,3&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlM2FmYmQ1YWY2NTQ4MDAwMWNlMjI5OCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNTk2NzcxNzA3LCJleHAiOjE1OTkzNjQ3ODV9.jbpUQpDgH0dE-2NgmTd93D-Cbsb4WdTbkqRCAC9GxMk&clientChannel=appstore&clientType=ios-app&environment=release&exerciseDebug=0",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807获取第一节习题().test_start()
