# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807摸底测试结果页.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807摸底测试结果页(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam")
            .get(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam"
            )
            .with_params(
                **{
                    "lessonType": "preExam",
                    "lessonModuleId": "5f2ccfe6785684e418d8c2ad",
                    "classId": "5f0dbf07e08ce8fed7fa97d0",
                    "testPaperId": "e8810cf0-c0fa-11ea-80eb-57f4065adad0",
                    "lessonId": "5f2ccfe6785684d9e2d8c2ac",
                    "isOpen": "false",
                }
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "referer": "https://yangcong345.com/mp_exercise/app/exam",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4NTE1fQ.JONS1rA_ks6frlVceweodThT3RT8bLdGnKwyy93JgEc",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807摸底测试结果页().test_start()
