# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807提交完成结课测评.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807提交完成结课测评(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/user-lesson-learn/cb-exam-submit")
            .post(
                "https://api-wx.yangcong345.com/primary_account/user-lesson-learn/cb-exam-submit"
            )
            .with_headers(
                **{
                    "accept": "application/json",
                    "origin": "https://yangcong345.com",
                    "content-type": "application/json;charset=UTF-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4",
                    "referer": "https://yangcong345.com/mp_exercise/app/exam",
                    "content-length": "940",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .with_json(
                {
                    "lessonModuleId": "5f2ccfe7785684f9bbd8c2d7",
                    "lessonType": "finalExam",
                    "classId": "5f0dbf07e08ce8fed7fa97d0",
                    "testPaperId": "7bd1e920-c0fb-11ea-8045-b12bc88dde59",
                    "lessonId": "5f2ccfe7785684c637d8c2d6",
                    "answers": [
                        {
                            "id": "89a32f20-bac8-11ea-b304-9d39d7980efd",
                            "score": 12.5,
                            "answer": ["$6$"],
                            "state": True,
                        },
                        {
                            "id": "d17babb0-bac8-11ea-b304-9d39d7980efd",
                            "score": 12.5,
                            "answer": ["$12$"],
                            "state": True,
                        },
                        {
                            "id": "2c199b90-bac9-11ea-9f46-ef372990082a",
                            "score": 12.5,
                            "answer": ["$33$"],
                            "state": False,
                        },
                        {
                            "id": "73eaec30-bac9-11ea-9f46-ef372990082a",
                            "score": 12.5,
                            "answer": ["$66$"],
                            "state": False,
                        },
                        {
                            "id": "986c7920-bac9-11ea-9f46-ef372990082a",
                            "score": 12.5,
                            "answer": ["$36$"],
                            "state": False,
                        },
                        {
                            "id": "b21f9af0-bac9-11ea-b61d-a3008e97814e",
                            "score": 12.5,
                            "answer": ["$66$"],
                            "state": False,
                        },
                        {
                            "id": "cd64ce70-bac9-11ea-9f46-ef372990082a",
                            "score": 12.5,
                            "answer": ["$22$"],
                            "state": False,
                        },
                        {
                            "id": "03eceb80-baca-11ea-9f46-ef372990082a",
                            "score": 12.5,
                            "answer": ["$8$", "$6$"],
                            "state": False,
                        },
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807提交完成结课测评().test_start()
