# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/0806提交视频信息.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0806提交视频信息(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/submitVideo")
            .post(
                "https://api-primary.yangcong345.com/primary_account/course/submitVideo"
            )
            .with_headers(
                **{
                    "content-length": "201",
                    "accept": "application/json, text/plain, */*",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJwY0g1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MjIyNjc2fQ.XqpHj1HznASsyQP0flOT6XIVhyZqGzfBe4u9Qe9aXfI",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://yangcong345.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://yangcong345.com/xiaoxue/goals?goalMode=1595779200000&v=2&index=0&m=week",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "topicId": "54a7e77a-6e26-11e8-a26d-f3cbfab29952",
                    "watchTime": "332.58",
                    "classId": "5f0fcc66e1e362742885f1fc",
                    "platform": "web",
                    "lessonId": "5f07e38d109513bdac9acc79",
                    "moduleId": "5f0d7169be6547963e9c7256",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.result", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0806提交视频信息().test_start()
