# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807大课结课报告.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807大课结课报告(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/learnReport/course/end-report")
            .get(
                "https://api-wx.yangcong345.com/primary_account/learnReport/course/end-report"
            )
            .with_params(
                **{
                    "platform": "app",
                    "classId": "5f0dbf98e08ce80fd5fa97d7",
                    "moduleId": "5f2ccc2378568434f8d8c1a7",
                    "lessonId": "5f2ccc23785684fd60d8c1a6",
                }
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/endReport",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA3NzIwfQ.263AjO-3m2-q0K1vuz1Ad-q-NPnduXRpRntEFfkGJIw",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807大课结课报告().test_start()
