# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0806获取验证码.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0806获取验证码(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/passport/sendCaptcha")
            .post(
                "https://api-primary.yangcong345.com/primary_account/passport/sendCaptcha"
            )
            .with_headers(
                **{
                    "content-length": "257",
                    "accept": "application/json, text/plain, */*",
                    "x-crypto-api": "true",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://yangcong345.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://yangcong345.com/xiaoxue/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .with_json(
                {
                    "sign": "8DC28CF98E911AFF61456391ECDBF8A65F2CC007primary",
                    "context": "VTJGc2RHVmtYMTlCZzBud3hySXAzZHQvbFJVbVFNNlZJY2JkQzhLbU8zYXY1ZWw2bmtOR1c1dnVrUGhkQjhVa1JEYkN5QXNzUytBUUpnN1M2N3poVGIzSU9yV1JXRVNOUnBWSWIwSys1K0RBUDhjWC9hL2hCNDUxWWZURkV0bHk=",
                    "crypto": True,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.crypto", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0806获取验证码().test_start()
