# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/0807进入正式讲次.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0807进入正式讲次(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/lesson/5f2ccfe678568420a4d8c2b3")
            .get(
                "https://api-wx.yangcong345.com/primary_account/course/lesson/5f2ccfe678568420a4d8c2b3"
            )
            .with_params(**{"classId": "5f0dbf07e08ce8fed7fa97d0", "platform": "app"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/cv2/lessonInfo",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI4MzA4Nzc1fQ.OOiPwEwLAr4cfu31I2yuOdhRjg6i7W1JKm08TmOaqv4",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0807进入正式讲次().test_start()
