# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0817后台葱钻订单定向查询.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0817后台葱钻订单定向查询(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/shadow/coin-order/orders")
            .get(
                "https://api-primary-test.yangcong345.com/primary_account/shadow/coin-order/orders"
            )
            .with_params(**{"phone": "18524635227"})
            .with_headers(
                **{
                    "Host": "api-primary-test.yangcong345.com",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "ShadowAuthorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjMDc0NzM3MTdjNTRiMDVhZGI1NWViNSIsImlhdCI6MTU5NzI5OTM3NywiZXhwIjoxNTk4NTA4OTc3fQ.0J0zdg5ZbsS3oLjNpfxXn-X20jVfPws5EMwNQfX9W9E",
                    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjMDc0NzM3MTdjNTRiMDVhZGI1NWViNSIsImlhdCI6MTU5NzI5OTM3NywiZXhwIjoxNTk4NTA4OTc3fQ.0J0zdg5ZbsS3oLjNpfxXn-X20jVfPws5EMwNQfX9W9E",
                    "Range": "items=0-19",
                    "Accept": "*/*",
                    "Origin": "http://10.8.8.8",
                    "Sec-Fetch-Site": "cross-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "http://10.8.8.8/admin7/dimand/order",
                    "Accept-Encoding": "identity",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 206)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0817后台葱钻订单定向查询().test_start()
