# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0819获取用户报名信息.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0819获取用户报名信息(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_enrollment/api/enrollmentPlan/getPlanUserLogByLogId")
            .get(
                "https://api-primary.yangcong345.com/primary_enrollment/api/enrollmentPlan/getPlanUserLogByLogId"
            )
            .with_params(**{"planUserLogId": "254849"})
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Linux; Android 9; V1813BT Build/PKQ1.181030.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/8.1.14.2",
                    "origin": "https://yangcong345.com",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZGMyODY1MDFlODZmMDBmNWY0OWZiNjciLCJwaG9uZSI6IjE4NDA0OTEyNzY5IiwicGxhdGZvcm0iOiJ1bmtub3duIiwid2VjaGF0SWQiOjM3NTYzNCwiZXhwIjoxNjI5MzU2ODk0fQ.kpQZqEbb06pQK-5e4Nj-YYLbTpmb4SbqqQtMGAh0VWo",
                    "accept": "*/*",
                    "referer": "https://yangcong345.com/pg/p/result?ycfrom=xsapp-1&orderId=5f3ccfdf0aaf0d2fa24c6794",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,en-US;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0819获取用户报名信息().test_start()
