# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0817兑换成功订单.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0817兑换成功订单(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/coin-mall/coin-order/order")
            .post(
                "https://api-primary.yangcong345.com/primary_account/coin-mall/coin-order/order"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "content-type": "application/json;charset=utf-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI5MTcyNjM0fQ.RRFyl9hHLt3VNxApA60RPQxR8QEhoL5aii8YxCBDXmw",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/study/confirmExchange",
                    "content-length": "1027",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .with_json(
                {
                    "goodId": "4648634c-2753-49ba-a31d-34f8b9f875cb",
                    "amount": 1,
                    "price": 1999,
                    "address": {
                        "_id": "5ece0d19517c1b3642c897cb",
                        "updatedAt": "2020-08-17T03:58:25.784Z",
                        "createdAt": "2020-05-27T06:47:53.020Z",
                        "userId": "5e3afbd5af65480001ce2298",
                        "phone": "18524635227",
                        "name": "😒内部测试",
                        "province": "北京市",
                        "city": "北京市",
                        "district": "朝阳区",
                        "address": "洋葱数学",
                        "isDefault": True,
                        "__v": 0,
                    },
                    "goodsSnap": {
                        "id": "4648634c-2753-49ba-a31d-34f8b9f875cb",
                        "name": "冰箱贴（内含20个）",
                        "skus": None,
                        "coverPicture": "https://wx-static.yangcong345.com/ps/malls_illus_refrigerator_magnet@3x.png",
                        "description": "创意可爱动物冰箱贴，有他在就不用担心零碎纸片找不到，贴名片、贴标签、贴照片、图案漂亮，具有超赞的装饰作用",
                        "pictures": [
                            "https://wx-static.yangcong345.com/ps/img_detail_refrigerator_magnet@2x.png"
                        ],
                        "price": "1999",
                        "state": 1,
                        "type": 1,
                        "kind": "refrigerator_magnet",
                        "kindParam": {},
                        "createdAt": "2020-04-27T16:37:28.337Z",
                        "updatedAt": "2020-04-27T16:37:28.337Z",
                        "saleNum": 275,
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.result", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0817兑换成功订单().test_start()
