# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0817App葱钻获得记录.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0817App葱钻获得记录(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/course/walletChangeList")
            .get(
                "https://api-primary.yangcong345.com/primary_account/course/walletChangeList"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/study/commoditiesList",
                    "accept-encoding": "identity",
                    "range": "item=0-19",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI5MTcyMTYzfQ.iipWATnt5rsXCA4RS_58HPWzLiOlQnJy2CBJW6OnPTA",
                }
            )
            .validate()
            .assert_equal("status_code", 206)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0817App葱钻获得记录().test_start()
