# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0819获取招生细则详情.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0819获取招生细则详情(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_enrollment/api/enrollmentPlan/getEnrollmentDetailList")
            .get(
                "https://api-primary.yangcong345.com/primary_enrollment/api/enrollmentPlan/getEnrollmentDetailList"
            )
            .with_params(**{"planId": "131"})
            .with_headers(
                **{
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZGMyODY1MDFlODZmMDBmNWY0OWZiNjciLCJwaG9uZSI6IjE4NDA0OTEyNzY5IiwicGxhdGZvcm0iOiJ1bmtub3duIiwid2VjaGF0SWQiOjM3MzM4NSwiZXhwIjoxNjI4NjEyMTY2fQ.ozxQjBeVxEEuxykRMiis_RM22lG_4Y21lb0LJSHtJPI",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://yangcong345.com/pg/e?planId=131&ycfrom=xsapp-1",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "if-none-match": 'W/"70a1-NLQRlLdUmtcYjAzZxHTmZZNDHKI"',
                }
            )
            .validate()
            .assert_equal("status_code", 304)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0819获取招生细则详情().test_start()
