# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0817后台减少葱钻.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0817后台减少葱钻(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/shadow/handleUserWallet")
            .post(
                "https://api-primary-test.yangcong345.com/primary_account/shadow/handleUserWallet"
            )
            .with_headers(
                **{
                    "Host": "api-primary-test.yangcong345.com",
                    "Connection": "keep-alive",
                    "Content-Length": "127",
                    "Accept": "application/json",
                    "ShadowAuthorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjMDczZTkxNzMzYzkyMTYxODhjNDlkYSIsImlhdCI6MTU5NjQ0MjAzMCwiZXhwIjoxNTk3NjUxNjMwfQ.s7KdF9cppQBtgd2-A6rKX57IwQZ3UGw7PU9wJcBb7sc",
                    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjMDczZTkxNzMzYzkyMTYxODhjNDlkYSIsImlhdCI6MTU5NjQ0MjAzMCwiZXhwIjoxNTk3NjUxNjMwfQ.s7KdF9cppQBtgd2-A6rKX57IwQZ3UGw7PU9wJcBb7sc",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Origin": "http://10.8.8.8",
                    "Sec-Fetch-Site": "cross-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "http://10.8.8.8/admin7/dimand/manage",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "type": "consume",
                    "mount": 1,
                    "extra": "自动化测试",
                    "userId": "5d08d7487953731d75197c4c",
                    "classId": "5f0d5cf2c192bf87760b4297",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.result", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0817后台减少葱钻().test_start()
