# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0817获取省市编号.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0817获取省市编号(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/goods/getRegion")
            .get("https://api-primary.yangcong345.com/primary_account/goods/getRegion")
            .with_params(**{"regionCode": "0", "type": ""})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/address",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI5MTcyNjM0fQ.RRFyl9hHLt3VNxApA60RPQxR8QEhoL5aii8YxCBDXmw",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.ok", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0817获取省市编号().test_start()
