# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0819获取用户信息.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0819获取用户信息(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/passport/getUserInfo")
            .get(
                "https://api-primary.yangcong345.com/primary_account/passport/getUserInfo"
            )
            .with_params(
                **{
                    "sign": "02D05512165F71116C8A527532F31CF35F3CCD36primary",
                    "context": "VTJGc2RHVmtYMSt4OThUa29qZzBpTVd3VERob3RPTXpPeGZqdkZ5elFoZVB5V0dPeE85R1JaVmtlaVBaaTIxYg==",
                    "crypto": "true",
                }
            )
            .with_headers(
                **{
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZGMyODY1MDFlODZmMDBmNWY0OWZiNjciLCJwaG9uZSI6IjE4NDA0OTEyNzY5IiwicGxhdGZvcm0iOiJ1bmtub3duIiwid2VjaGF0SWQiOjM3MzM4NSwiZXhwIjoxNjI4NjEyMTY2fQ.ozxQjBeVxEEuxykRMiis_RM22lG_4Y21lb0LJSHtJPI",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
                    "x-crypto-api": "true",
                    "accept": "*/*",
                    "origin": "https://yangcong345.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://yangcong345.com/pg/e?planId=131&ycfrom=xsapp-1",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)

            .assert_equal("body.crypto", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0819获取用户信息().test_start()
