# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0819购课成功页获取班级老师信息.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0819购课成功页获取班级老师信息(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        
            Step(RunRequest("/primary_account/assignClass/getClass").post("https://api-primary.yangcong345.com/primary_account/assignClass/getClass").with_headers(**{'content-length': '38', 'accept': 'application/json', 'origin': 'https://yangcong345.com', 'user-agent': 'Mozilla/5.0 (Linux; Android 9; V1813BT Build/PKQ1.181030.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/8.1.14.2', 'authorization': 'eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZGMyODY1MDFlODZmMDBmNWY0OWZiNjciLCJwaG9uZSI6IjE4NDA0OTEyNzY5IiwicGxhdGZvcm0iOiJ1bmtub3duIiwid2VjaGF0SWQiOjM3NTYzNCwiZXhwIjoxNjI5MzU2ODk0fQ.kpQZqEbb06pQK-5e4Nj-YYLbTpmb4SbqqQtMGAh0VWo', 'content-type': 'application/json;charset=UTF-8', 'referer': 'https://yangcong345.com/pg/p/result?ycfrom=xsapp-1&orderId=5f3ccfdf0aaf0d2fa24c6794', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'zh-CN,en-US;q=0.9'}).with_json({'classId': '5f364e266172db48942d45ef'}).validate().assert_equal("status_code", 200).assert_equal("body.code", 0)),
        
    ]

if __name__ == "__main__":
    TestCaseT0819购课成功页获取班级老师信息().test_start()
