# NOTE: Generated By HttpRunner v3.0.12
# FROM: har/0817更换地址2.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT0817更换地址2(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_account/userAddress/address")
            .put(
                "https://api-primary.yangcong345.com/primary_account/userAddress/address"
            )
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://h5-v5-0.yangcong345.com",
                    "content-type": "application/json;charset=utf-8",
                    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJ5aWQiOiI1ZTNhZmJkNWFmNjU0ODAwMDFjZTIyOTgiLCJwaG9uZSI6IjE4NTI0NjM1MjI3IiwicGxhdGZvcm0iOiJhcHBMZWFybkg1Iiwid2VjaGF0SWQiOjE5NTIzMSwiZXhwIjoxNjI5MTcyNjM0fQ.RRFyl9hHLt3VNxApA60RPQxR8QEhoL5aii8YxCBDXmw",
                    "referer": "https://h5-v5-0.yangcong345.com/xs-app/address",
                    "content-length": "174",
                    "accept-language": "zh-cn",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .with_json(
                {
                    "phone": "18524635227",
                    "name": "内部测试",
                    "province": "北京市",
                    "city": "北京市",
                    "district": "朝阳区",
                    "address": "洋葱数学",
                    "addressId": "5ece0d19517c1b3642c897cb",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT0817更换地址2().test_start()
