# NOTE: Generated By HttpRunner v3.1.2
# FROM: har/招生计划详情列表.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase招生计划详情列表(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/primary_enrollment/api/enrollmentPlan/getEnrollmentDetailList")
            .get(
                "https://api-wx.yangcong345.com/primary_enrollment/api/enrollmentPlan/getEnrollmentDetailList"
            )
            .with_params(**{"planId": "98"})
            .with_headers(
                **{
                    "appinstallchannel": "yangcong",
                    "accept": "application/json, text/plain, */*",
                    "origin": "https://yangcong345.com",
                    "user-agent": "Mozilla/5.0 (Linux; Android 5.1.1; vmos Build/LMY48G; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36",
                    "referer": "https://yangcong345.com/xs-h5/course-plan?appVersion=5.29.0&channel=yangcong&from=DialogBox&planId=98&primaryPlatform=appLearnH5&userId=5ebb670226002e00017e470d&ycfrom=DialogBox&deviceId=fcf6c66211e195fd&device=fcf6c66211e195fd&platform=android&exerciseDebug=0&clientType=android-app&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlYmI2NzAyMjYwMDJlMDAwMTdlNDcwZCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNTkyMzgyMDQyLCJleHAiOjE1OTYzNTA2NzN9.g0FImG-pDWrKBt8Tft6zxSViyFVT2vrW0fdXr0FXy4A&clientChannel=yangcong&environment=release&appCategory=student&phoneModel=vmos&env=prod",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.8",
                    "x-requested-with": "com.yangcong345.android.phone",
                    "if-none-match": 'W/"32e9-3QsFl3yB0VhQdK5Je9c3ivBoxMI"',
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCase招生计划详情列表().test_start()
